"use client";
import { useState } from "react";
import {
  Brain, Download, Copy, Check, Settings, Sparkles,
  Zap, FileCode2
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import ToolLayout from "@/components/ToolLayout";
import ToolGuide from "@/components/ToolGuide";

interface AgentForm {
  name: string;
  role: string;
  skills: string;
  style: string;
  instructions: string;
  persona: string;
  outputFormat: string;
}

const SKILL_PRESETS = [
  { label: "Full-Stack Dev", skills: "React/Next.js\nNode.js/TypeScript\nREST API Design\nDatabase Optimization\nCI/CD Pipelines" },
  { label: "Data Analyst", skills: "Python/Pandas\nSQL & NoSQL\nData Visualization\nStatistical Analysis\nML Fundamentals" },
  { label: "Content Writer", skills: "SEO Copywriting\nBrand Voice Adaptation\nLong-form Articles\nSocial Media Content\nTechnical Documentation" },
  { label: "AI Researcher", skills: "Prompt Engineering\nLLM Fine-tuning\nRAG Architecture\nAI Ethics\nBenchmark Evaluation" },
];

export default function ClaudeSkillsClient() {
  const [form, setForm] = useState<AgentForm>({
    name: "", role: "", skills: "", style: "", instructions: "", persona: "", outputFormat: ""
  });
  const [copied, setCopied] = useState(false);
  const [activeTab, setActiveTab] = useState<"Identity" | "Training" | "Behavior">("Identity");

  const update = (key: keyof AgentForm, val: string) => setForm(prev => ({ ...prev, [key]: val }));

  const generateMarkdown = (): string => {
    const { name, role, skills, style, instructions, persona, outputFormat } = form;
    if (!name && !role) return "### Fill in the form to generate your SKILLS.md file";

    const skillLines = skills.trim()
      ? skills.split("\n").filter(Boolean).map(s => `- ${s.trim()}`).join("\n")
      : "- List key skills here";

    const instructionLines = instructions.trim()
      ? instructions.split("\n").filter(Boolean).map(i => `- ${i.trim()}`).join("\n")
      : "- Always cite sources when making factual claims\n- Decline requests that violate ethical guidelines";

    return `---
name: ${name || "My AI Agent"}
description: ${role || "A specialized AI agent"}
version: "1.0.0"
author: "CosmoxHub Agent Builder"
---

# ${name || "My AI Agent"} — Agent Persona & Skills

## 🎭 Identity & Persona
${persona || `${name || "This agent"} is a highly capable AI assistant with deep expertise in its domain. It approaches every task with precision, care, and a commitment to delivering maximum value.`}

## 🎯 Primary Role & Mission
${role || "Describe the agent's primary purpose and mission here."}

## 🚀 Core Capabilities
${skillLines}

## 🗣️ Communication Style & Tone
${style || "Professional, clear, and concise. Adapts communication style to match the user's expertise level."}

## 📋 Output Format Preferences
${outputFormat || "Structured responses with clear sections, bullet points for lists, and code blocks for technical content."}

## 🛡️ Critical Instructions & Guardrails
${instructionLines}

---
*Generated by [CosmoxHub](https://cosmoxhub.com) Elite Agent Skills Builder*
*Compatible with: Claude, GPT-4, Gemini, and all major frontier models*`;
  };

  const downloadFile = () => {
    const content = generateMarkdown();
    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${form.name.toLowerCase().replace(/\s+/g, "_") || "agent"}_skills.md`;
    document.body.appendChild(a); a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateMarkdown());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const applyPreset = (preset: typeof SKILL_PRESETS[0]) => {
    update("skills", preset.skills);
  };

  const hasContent = !!(form.name || form.role);

  return (
    <ToolLayout
      title="Elite AI Agent Builder"
      description="Design professional SKILLS.md files for Claude, GPT-4, and Gemini. Define roles, capabilities, and guardrails in a structured format."
      icon={Brain} color="#a855f7"
    >
      <div className="grid lg:grid-cols-[1.2fr_0.8fr] gap-8 items-start">
        <div className="space-y-6">
          <div className="bg-white/[0.03] border border-white/10 rounded-[2.5rem] p-8 shadow-2xl relative">
            <div className="flex items-center justify-between mb-8 pb-6 border-b border-white/5">
              <div className="flex items-center gap-3">
                <div className="p-2.5 bg-violet-500/10 rounded-2xl"><Settings className="w-5 h-5 text-violet-500" /></div>
                <h3 className="text-xl font-black text-white tracking-tight italic">Agent Configuration</h3>
              </div>
              <div className="flex items-center gap-6 bg-white/[0.02] p-2 rounded-2xl border border-white/5 ml-12">
                {(["Identity", "Training", "Behavior"] as const).map(tab => (
                  <button 
                    key={tab} 
                    onClick={() => setActiveTab(tab)}
                    className={`px-8 py-3 text-[12px] font-black uppercase tracking-[0.2em] rounded-xl transition-all shrink-0 ${activeTab === tab ? "bg-violet-600 text-white shadow-[0_8px_30px_rgba(139,92,246,0.4)] scale-105" : "text-slate-500 hover:text-slate-300 hover:bg-white/5 opacity-60 hover:opacity-100"}`}
                  >
                    {tab}
                  </button>
                ))}
              </div>
            </div>

            <div className="space-y-8 min-h-[450px]">
              <AnimatePresence mode="wait">
                {activeTab === "Identity" && (
                  <motion.div key="identity" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }} className="space-y-6">
                    <div className="space-y-3">
                      <label className="text-slate-500 text-[10px] font-black uppercase tracking-[0.2em] flex items-center gap-2">Agent Name</label>
                      <input type="text" value={form.name} onChange={e => update("name", e.target.value)} placeholder="CodeArchitect, ResearchMaster..."
                        className="w-full bg-white/5 border border-white/10 rounded-2xl px-6 py-5 text-sm text-white focus:border-violet-500/40 outline-none transition-all font-medium placeholder:text-slate-800 shadow-inner" />
                    </div>
                    <div className="space-y-3">
                      <label className="text-slate-500 text-[10px] font-black uppercase tracking-[0.2em]">Primary Mission</label>
                      <textarea value={form.role} onChange={e => update("role", e.target.value)} placeholder="What is this agent's core purpose? What problem does it solve?"
                        className="w-full bg-white/5 border border-white/10 rounded-2xl px-6 py-5 text-sm text-white focus:border-violet-500/40 outline-none transition-all font-medium placeholder:text-slate-800 resize-none h-32 shadow-inner" />
                    </div>
                    <div className="space-y-3">
                      <label className="text-slate-500 text-[10px] font-black uppercase tracking-[0.2em]">Persona Description</label>
                      <textarea value={form.persona} onChange={e => update("persona", e.target.value)} placeholder="Describe the agent's character and expertise level..."
                        className="w-full bg-white/5 border border-white/10 rounded-2xl px-6 py-5 text-sm text-white focus:border-violet-500/40 outline-none transition-all font-medium placeholder:text-slate-800 resize-none h-32 shadow-inner" />
                    </div>
                  </motion.div>
                )}

                {activeTab === "Training" && (
                  <motion.div key="training" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }} className="space-y-6">
                    <div className="space-y-4">
                      <div className="flex items-center justify-between">
                        <label className="text-slate-500 text-[10px] font-black uppercase tracking-[0.2em]">Quick Presets</label>
                      </div>
                      <div className="grid grid-cols-2 lg:grid-cols-4 gap-2">
                        {SKILL_PRESETS.map(p => (
                          <button key={p.label} onClick={() => applyPreset(p)}
                            className="px-4 py-3 bg-white/5 hover:bg-violet-600/20 border border-white/5 hover:border-violet-500/40 rounded-xl text-[9px] font-black text-slate-400 hover:text-violet-400 uppercase tracking-widest transition-all">
                            {p.label}
                          </button>
                        ))}
                      </div>
                    </div>
                    <div className="space-y-3">
                      <label className="text-slate-500 text-[10px] font-black uppercase tracking-[0.2em]">Core Capabilities (one per line)</label>
                      <textarea value={form.skills} onChange={e => update("skills", e.target.value)} placeholder="React/Next.js\nPython Data Analysis\nSEO Strategy\n..."
                        className="w-full bg-white/5 border border-white/10 rounded-2xl px-6 py-5 text-sm text-white focus:border-violet-500/40 outline-none transition-all font-medium font-mono placeholder:text-slate-800 resize-none h-64 shadow-inner" />
                    </div>
                  </motion.div>
                )}

                {activeTab === "Behavior" && (
                  <motion.div key="behavior" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }} className="space-y-6">
                    <div className="space-y-3">
                      <label className="text-slate-500 text-[10px] font-black uppercase tracking-[0.2em]">Communication Tone</label>
                      <input type="text" value={form.style} onChange={e => update("style", e.target.value)} placeholder="Professional yet approachable, Concise and direct..."
                        className="w-full bg-white/5 border border-white/10 rounded-2xl px-6 py-5 text-sm text-white focus:border-violet-500/40 outline-none transition-all font-medium placeholder:text-slate-800 shadow-inner" />
                    </div>
                    <div className="space-y-3">
                      <label className="text-slate-500 text-[10px] font-black uppercase tracking-[0.2em]">Output Preferences</label>
                      <input type="text" value={form.outputFormat} onChange={e => update("outputFormat", e.target.value)} placeholder="Markdown with headers, JSON responses..."
                        className="w-full bg-white/5 border border-white/10 rounded-2xl px-6 py-5 text-sm text-white focus:border-violet-500/40 outline-none transition-all font-medium placeholder:text-slate-800 shadow-inner" />
                    </div>
                    <div className="space-y-3">
                      <label className="text-slate-500 text-[10px] font-black uppercase tracking-[0.2em]">Guardrails & Ethics (one per line)</label>
                      <textarea value={form.instructions} onChange={e => update("instructions", e.target.value)} placeholder="Always cite sources\nDecline unethical requests..."
                        className="w-full bg-white/5 border border-white/10 rounded-2xl px-6 py-5 text-sm text-white focus:border-violet-500/40 outline-none transition-all font-medium placeholder:text-slate-800 resize-none h-44 shadow-inner" />
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          </div>
        </div>

        <div className="space-y-5 sticky top-8">
          <div className="bg-white/[0.03] border border-violet-500/20 rounded-[2.5rem] overflow-hidden shadow-2xl">
            <div className="px-6 py-4 border-b border-white/5 flex items-center justify-between bg-violet-500/[0.03]">
              <div className="flex items-center gap-2">
                <FileCode2 size={13} className="text-violet-400" />
                <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Live Preview · SKILLS.md</span>
              </div>
              <div className="flex items-center gap-2">
                <button onClick={handleCopy} className={`flex items-center gap-2 px-5 py-2.5 rounded-xl text-[10px] font-black uppercase tracking-widest border transition-all ${copied ? "bg-emerald-500/15 text-emerald-400 border-emerald-500/30" : "bg-white/5 text-slate-400 border-white/10 hover:border-violet-500/30 hover:text-violet-400"}`}>
                  {copied ? <Check size={12} /> : <Copy size={12} />}
                  {copied ? "COPIED" : "COPY"}
                </button>
              </div>
            </div>

            <pre className="p-8 text-slate-300 text-[11px] font-mono whitespace-pre-wrap min-h-[500px] leading-relaxed overflow-auto max-h-[600px] selection:bg-violet-500/40">
              {generateMarkdown()}
            </pre>
          </div>

          <button onClick={downloadFile} disabled={!hasContent}
            className="w-full py-5 bg-violet-600 text-white font-black rounded-2xl shadow-[0_4px_30px_rgba(139,92,246,0.3)] hover:shadow-[0_4px_40px_rgba(139,92,246,0.5)] hover:-translate-y-1 transition-all disabled:opacity-40 disabled:translate-y-0 disabled:shadow-none flex items-center justify-center gap-3 uppercase tracking-[0.2em] text-xs">
            <Download size={18} /> Download skills.md
          </button>

          <div className="p-6 bg-white/[0.02] border border-white/5 rounded-3xl flex items-start gap-4">
            <Zap size={16} className="text-violet-500 shrink-0 mt-0.5" />
            <p className="text-[10px] text-slate-500 font-bold leading-relaxed uppercase tracking-widest">
              Generated files are compatible with Claude, GPT-4, and Gemini system protocols.
            </p>
          </div>
        </div>
      </div>

      <div className="mt-20 border-t border-white/5 pt-20">
        <ToolGuide
          toolName="Claude Skills Creator"
          sections={[
            {
              title: "Construct Agent Identity",
              content: "Specify the name and primary mission of your AI agent. Our builder helps you define a clear raison d'être for any specialized task."
            },
            {
              title: "Define Core Capabilities",
              content: "List the specific skills and domain knowledge your agent must possess. Use our role-based presets for rapid full-stack or research profiling."
            },
            {
              title: "Configure Behavior Logic",
              content: "Set the communication tone, output preferences, and ethical guardrails. This ensures your agent remains helpful, professional, and secure."
            },
            {
              title: "Export Professional Specs",
              content: "Instantly generate a structured SKILLS.md file. Use our live preview to audit the definition before downloading for deployment."
            }
          ]}
          faqs={[
            {
              question: "Is my agent definition kept private?",
              answer: "Absolutely. CosmoxHub utilizes local processing for all agent definitions. Your proprietary skills and instructions never leave your browser."
            },
            {
              question: "What is a SKILLS.md file used for?",
              answer: "It is an industry-standard structure for defining AI agent capabilities. It can be used as a system prompt or a context file for agents like Claude and GPT."
            },
            {
              question: "Can I use these skills for other AI models?",
              answer: "Yes. While optimized for Claude's reasoning patterns, the structured markdown is highly effective for GPT-4, Gemini, and various Llama-based models."
            }
          ]}
        />

        <div className="mt-20 prose prose-invert max-w-none border border-white/5 bg-white/[0.02] p-12 rounded-[3rem]">
          <h2 className="text-3xl font-black text-white uppercase tracking-tighter mb-8">Engineering Elite AI Personas with Precision</h2>
          <div className="grid md:grid-cols-2 gap-10 text-slate-400 text-sm leading-relaxed font-medium">
            <div className="space-y-4">
              <p>
                As AI becomes more integrated into professional workflows, the need for specialized, role-defined assistants is paramount. CosmoxHub's <span className="text-white font-bold">secure AI agent builder</span> provides the ultimate lab for engineering high-fidelity SKILLS.md files. This <span className="text-purple-500 font-bold underline">free online utility tool</span> empowers developers to define personas with surgical precision.
              </p>
              <p>
                We are proud to offer the <span className="text-white font-bold">fastest SKILLS.md generator</span> for the modern AI ecosystem. By prioritizing <span className="text-white font-bold">local processing</span>, we ensure that your agent's core capabilities and proprietary guardrails are never exposed to external servers, maintaining 100% privacy for your AI architecture.
              </p>
            </div>
            <div className="space-y-4">
              <p>
                Our platform supports the most advanced prompt engineering frameworks, allowing you to build everything from elite full-stack developers to complex data analyst personas. The structured markdown output is compatible with all frontier models, ensuring your agent behaves with the specific tone and expertise level required for high-stakes professional environments.
              </p>
              <p>
                Join the vanguard of AI engineering by choosing CosmoxHub for your <span className="text-white font-bold">private, secure, and professional</span> agent definition needs. Master the art of the system prompt and deploy elite AI capabilities with confidence using our state-of-the-art builder.
              </p>
            </div>
          </div>
        </div>
      </div>
    </ToolLayout>
  );
}
