"use client";
import { useState } from "react";
import {
  Brain, Download, Copy, Check, Settings, Sparkles,
  Zap, ShieldCheck, FileCode2, User, Tag
} from "lucide-react";
import ToolLayout from "@/components/ToolLayout";
import { motion, AnimatePresence } from "framer-motion";

interface AgentForm {
  name: string;
  role: string;
  skills: string;
  style: string;
  instructions: string;
  persona: string;
  outputFormat: string;
}

const SKILL_PRESETS = [
  { label: "Full-Stack Dev", skills: "React/Next.js\nNode.js/TypeScript\nREST API Design\nDatabase Optimization\nCI/CD Pipelines" },
  { label: "Data Analyst", skills: "Python/Pandas\nSQL & NoSQL\nData Visualization\nStatistical Analysis\nML Fundamentals" },
  { label: "Content Writer", skills: "SEO Copywriting\nBrand Voice Adaptation\nLong-form Articles\nSocial Media Content\nTechnical Documentation" },
  { label: "AI Researcher", skills: "Prompt Engineering\nLLM Fine-tuning\nRAG Architecture\nAI Ethics\nBenchmark Evaluation" },
];

export default function ClaudeSkillsCreatorPage() {
  const [form, setForm] = useState<AgentForm>({
    name: "", role: "", skills: "", style: "", instructions: "", persona: "", outputFormat: ""
  });
  const [copied, setCopied] = useState(false);

  const update = (key: keyof AgentForm, val: string) => setForm(prev => ({ ...prev, [key]: val }));

  const generateMarkdown = (): string => {
    const { name, role, skills, style, instructions, persona, outputFormat } = form;
    if (!name && !role) return "### Fill in the form to generate your SKILLS.md file";

    const skillLines = skills.trim()
      ? skills.split("\n").filter(Boolean).map(s => `- ${s.trim()}`).join("\n")
      : "- List key skills here";

    const instructionLines = instructions.trim()
      ? instructions.split("\n").filter(Boolean).map(i => `- ${i.trim()}`).join("\n")
      : "- Always cite sources when making factual claims\n- Decline requests that violate ethical guidelines";

    return `---
name: ${name || "My AI Agent"}
description: ${role || "A specialized AI agent"}
version: "1.0.0"
author: "CosmoxHub Agent Builder"
---

# ${name || "My AI Agent"} — Agent Persona & Skills

## 🎭 Identity & Persona
${persona || `${name || "This agent"} is a highly capable AI assistant with deep expertise in its domain. It approaches every task with precision, care, and a commitment to delivering maximum value.`}

## 🎯 Primary Role & Mission
${role || "Describe the agent's primary purpose and mission here."}

## 🚀 Core Capabilities
${skillLines}

## 🗣️ Communication Style & Tone
${style || "Professional, clear, and concise. Adapts communication style to match the user's expertise level."}

## 📋 Output Format Preferences
${outputFormat || "Structured responses with clear sections, bullet points for lists, and code blocks for technical content."}

## 🛡️ Critical Instructions & Guardrails
${instructionLines}

---
*Generated by [CosmoxHub](https://cosmoxhub.com) Elite Agent Skills Builder*
*Compatible with: Claude, GPT-4, Gemini, and all major frontier models*`;
  };

  const downloadFile = () => {
    const content = generateMarkdown();
    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${form.name.toLowerCase().replace(/\s+/g, "_") || "agent"}_skills.md`;
    document.body.appendChild(a); a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateMarkdown());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const applyPreset = (preset: typeof SKILL_PRESETS[0]) => {
    update("skills", preset.skills);
  };

  const hasContent = !!(form.name || form.role);

  return (
    <ToolLayout
      title="Elite AI Agent Builder"
      description="Design professional SKILLS.md files for Claude, GPT-4, and Gemini. Define roles, capabilities, and guardrails in a structured format."
      icon={Brain} color="#a855f7"
    >
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({
        "@context": "https://schema.org", "@type": "SoftwareApplication",
        "name": "CosmoxHub Elite AI Agent Skills Builder",
        "operatingSystem": "Any", "applicationCategory": "DeveloperTool",
        "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" },
        "featureList": ["SKILLS.md generator", "Skill presets", "Live preview", "Multi-model compatible", "One-click export"]
      })}} />

      <div className="grid lg:grid-cols-[1fr_1fr] gap-8 items-start">
        {/* Input Form */}
        <div className="space-y-5">
          <div className="bg-[#0a0a1a]/80 backdrop-blur-2xl border border-white/5 rounded-[2.5rem] p-8 shadow-2xl relative overflow-hidden">
            <div className="absolute top-0 left-0 w-full h-1.5 bg-gradient-to-r from-purple-600 to-violet-400 shadow-[0_2px_15px_rgba(168,85,247,0.4)]" />
            <div className="flex items-center gap-3 mb-8">
              <div className="p-2.5 bg-purple-500/10 rounded-2xl"><Settings className="w-5 h-5 text-purple-500" /></div>
              <h3 className="text-xl font-black text-white tracking-tight">Agent Configuration</h3>
            </div>

            <div className="space-y-6">
              {/* Agent Name */}
              <div className="space-y-2">
                <label className="text-slate-500 text-[10px] font-black uppercase tracking-widest flex items-center gap-2"><User size={11} className="text-purple-500" /> Agent Name</label>
                <input type="text" value={form.name} onChange={e => update("name", e.target.value)} placeholder="e.g. CodeArchitect, ResearchMaster, DataOracle"
                  className="w-full bg-white/5 border border-white/5 rounded-2xl px-5 py-4 text-sm text-white focus:border-purple-500/40 outline-none transition-all font-medium placeholder:text-slate-800" />
              </div>

              {/* Role */}
              <div className="space-y-2">
                <label className="text-slate-500 text-[10px] font-black uppercase tracking-widest flex items-center gap-2"><Tag size={11} className="text-purple-500" /> Primary Role & Mission</label>
                <textarea value={form.role} onChange={e => update("role", e.target.value)} placeholder="What is this agent's core purpose? What problem does it solve?"
                  className="w-full bg-white/5 border border-white/5 rounded-2xl px-5 py-4 text-sm text-white focus:border-purple-500/40 outline-none transition-all font-medium placeholder:text-slate-800 resize-none h-24" />
              </div>

              {/* Persona */}
              <div className="space-y-2">
                <label className="text-slate-500 text-[10px] font-black uppercase tracking-widest flex items-center gap-2"><Sparkles size={11} className="text-purple-500" /> Persona Description</label>
                <textarea value={form.persona} onChange={e => update("persona", e.target.value)} placeholder="Describe the agent's character, expertise level, and how it thinks..."
                  className="w-full bg-white/5 border border-white/5 rounded-2xl px-5 py-4 text-sm text-white focus:border-purple-500/40 outline-none transition-all font-medium placeholder:text-slate-800 resize-none h-24" />
              </div>

              {/* Skills with Presets */}
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <label className="text-slate-500 text-[10px] font-black uppercase tracking-widest flex items-center gap-2"><Zap size={11} className="text-purple-500" /> Skills (one per line)</label>
                  <span className="text-[9px] text-slate-600 font-bold uppercase">Presets →</span>
                </div>
                <div className="flex gap-2 flex-wrap mb-2">
                  {SKILL_PRESETS.map(p => (
                    <button key={p.label} onClick={() => applyPreset(p)}
                      className="px-3 py-1.5 bg-purple-500/10 hover:bg-purple-500/20 border border-purple-500/20 hover:border-purple-500/40 rounded-xl text-[9px] font-black text-purple-400 uppercase tracking-widest transition-all">
                      {p.label}
                    </button>
                  ))}
                </div>
                <textarea value={form.skills} onChange={e => update("skills", e.target.value)} placeholder={"React/Next.js\nPython Data Analysis\nSEO Strategy\n..."}
                  className="w-full bg-white/5 border border-white/5 rounded-2xl px-5 py-4 text-sm text-white focus:border-purple-500/40 outline-none transition-all font-medium font-mono placeholder:text-slate-800 resize-none h-28" />
              </div>

              {/* Communication Style */}
              <div className="space-y-2">
                <label className="text-slate-500 text-[10px] font-black uppercase tracking-widest">Communication Style</label>
                <input type="text" value={form.style} onChange={e => update("style", e.target.value)} placeholder="e.g. Professional yet approachable, Technical and precise, Concise and direct"
                  className="w-full bg-white/5 border border-white/5 rounded-2xl px-5 py-4 text-sm text-white focus:border-purple-500/40 outline-none transition-all font-medium placeholder:text-slate-800" />
              </div>

              {/* Output Format */}
              <div className="space-y-2">
                <label className="text-slate-500 text-[10px] font-black uppercase tracking-widest">Output Format Preferences</label>
                <input type="text" value={form.outputFormat} onChange={e => update("outputFormat", e.target.value)} placeholder="e.g. Markdown with headers, JSON responses, Code blocks with explanations"
                  className="w-full bg-white/5 border border-white/5 rounded-2xl px-5 py-4 text-sm text-white focus:border-purple-500/40 outline-none transition-all font-medium placeholder:text-slate-800" />
              </div>

              {/* Guardrails */}
              <div className="space-y-2">
                <label className="text-slate-500 text-[10px] font-black uppercase tracking-widest flex items-center gap-2"><ShieldCheck size={11} className="text-purple-500" /> Guardrails & Rules (one per line)</label>
                <textarea value={form.instructions} onChange={e => update("instructions", e.target.value)} placeholder={"Always cite sources\nDecline unethical requests\nAsk for clarification when ambiguous\n..."}
                  className="w-full bg-white/5 border border-white/5 rounded-2xl px-5 py-4 text-sm text-white focus:border-purple-500/40 outline-none transition-all font-medium placeholder:text-slate-800 resize-none h-24" />
              </div>
            </div>
          </div>
        </div>

        {/* Live Preview & Actions */}
        <div className="space-y-5 sticky top-8">
          <div className="bg-[#0a0a1a]/80 border border-purple-500/10 rounded-[2.5rem] overflow-hidden shadow-2xl">
            <div className="px-6 py-4 border-b border-white/5 flex items-center justify-between bg-purple-500/[0.03]">
              <div className="flex items-center gap-2">
                <FileCode2 size={13} className="text-purple-400" />
                <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Live Preview · SKILLS.md</span>
              </div>
              <div className="flex items-center gap-2">
                <button onClick={handleCopy} className={`flex items-center gap-2 px-4 py-2 rounded-xl text-[10px] font-black uppercase tracking-widest border transition-all ${copied ? "bg-emerald-500/15 text-emerald-400 border-emerald-500/30" : "bg-white/5 text-slate-400 border-white/10 hover:border-purple-500/30 hover:text-purple-400"}`}>
                  {copied ? <Check size={12} /> : <Copy size={12} />}
                  {copied ? "Copied!" : "Copy"}
                </button>
              </div>
            </div>

            <pre className="p-8 text-slate-300 text-xs font-mono whitespace-pre-wrap min-h-[500px] leading-relaxed overflow-auto max-h-[600px]">
              {generateMarkdown()}
            </pre>
          </div>

          {/* Action Buttons */}
          <button onClick={downloadFile} disabled={!hasContent}
            className="w-full py-5 bg-gradient-to-r from-purple-600 to-violet-600 text-white font-black rounded-2xl shadow-[0_4px_30px_rgba(168,85,247,0.3)] hover:shadow-[0_4px_40px_rgba(168,85,247,0.5)] hover:-translate-y-1 transition-all disabled:opacity-40 disabled:translate-y-0 disabled:shadow-none flex items-center justify-center gap-3 uppercase tracking-[0.15em] text-xs">
            <Download size={18} /> Download skills.md
          </button>

          <div className="p-6 bg-purple-500/5 border border-purple-500/10 rounded-3xl flex items-start gap-4">
            <Zap size={16} className="text-purple-500 shrink-0 mt-0.5" />
            <p className="text-[10px] text-slate-500 font-bold leading-relaxed uppercase tracking-wider">
              Generated files are fully compatible with Claude's SKILLS.md system, OpenAI Assistant instructions, and Gemini System Prompts.
            </p>
          </div>
        </div>
      </div>
    </ToolLayout>
  );
}
